var people = [{
    "id": 1,
    "first_name": "Morgen",
    "last_name": "Tuffrey",
    "email": "mtuffrey0@youtube.com",
    "gender": "Male",
    "ip_address": "198.29.51.183"
  }, {
    "id": 2,
    "first_name": "Allix",
    "last_name": "Spanton",
    "email": "aspanton1@addthis.com",
    "gender": "Female",
    "ip_address": "20.45.105.25"
  }, {
    "id": 3,
    "first_name": "Kit",
    "last_name": "Harbisher",
    "email": "kharbisher2@quantcast.com",
    "gender": "Female",
    "ip_address": "79.173.113.234"
  }, {
    "id": 4,
    "first_name": "Toinette",
    "last_name": "Tiptaft",
    "email": "ttiptaft3@ow.ly",
    "gender": "Female",
    "ip_address": "75.165.143.218"
  }, {
    "id": 5,
    "first_name": "Dominica",
    "last_name": "Fransson",
    "email": "dfransson4@dropbox.com",
    "gender": "Female",
    "ip_address": "21.42.94.23"
  }, {
    "id": 6,
    "first_name": "Cindelyn",
    "last_name": "Grunwall",
    "email": "cgrunwall5@berkeley.edu",
    "gender": "Female",
    "ip_address": "104.229.146.255"
  }, {
    "id": 7,
    "first_name": "Tim",
    "last_name": "Jekel",
    "email": "tjekel6@independent.co.uk",
    "gender": "Male",
    "ip_address": "166.240.90.182"
  }, {
    "id": 8,
    "first_name": "Binnie",
    "last_name": "Pound",
    "email": "bpound7@free.fr",
    "gender": "Female",
    "ip_address": "240.206.125.161"
  }, {
    "id": 9,
    "first_name": "Sayer",
    "last_name": "Fludder",
    "email": "sfludder8@liveinternet.ru",
    "gender": "Male",
    "ip_address": "161.87.99.138"
  }, {
    "id": 10,
    "first_name": "Loralee",
    "last_name": "Drexel",
    "email": "ldrexel9@over-blog.com",
    "gender": "Female",
    "ip_address": "83.38.195.13"
  }]

  module.exports = people;